GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My first post",
    "subject": "Post initial",
    "description": "Hello world" 
}